<!DOCTYPE html>
<html>
<head>
    <link
    	href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"rel="stylesheet">
    <style>
        body {
        	margin-top: 125px;
        }
        
        .nav {
        	margin-top: 28px;
        }
    </style>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD407G_68p0r5o6rNti4_-Upyt_pc17Gk0&sensor=true"></script>
<script type="text/javascript" src='//codeorigin.jquery.com/jquery-1.10.2.min.js'></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
</head>
<body>
	<div class='container'>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse"
						data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span> <span
							class="icon-bar"></span> <span class="icon-bar"></span> <span
							class="icon-bar"></span>
					</button>
					<!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
					<a class="navbar-brand logo-nav" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index')) ?>"><img
						src="http://placehold.it/150x75&text=Logo"></a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a
							href="<?php echo $this->url(array('controller'=>'company', 'action'=>'create'))?>">Company
								Signup</a></li>
						<li><a
							href="<?php echo $this->url(array('controller'=>'user', 'action'=>'create'))?>">User
								Signup</a></li>
					</ul>
				</div>
				<!-- /.navbar-collapse -->
			</div>
			<!-- /.container -->
		</nav>
            <?php echo $this->layout()->content; ?>
        </div>
</body>
</html>