<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD407G_68p0r5o6rNti4_-Upyt_pc17Gk0&sensor=true"></script>
        <script type="text/javascript" src='//codeorigin.jquery.com/jquery-1.10.2.min.js'></script>
        <link rel="stylesheet" href="/YHack/public/css/core.css"/>
        <link rel="stylesheet" href="/YHack/public/css/home.css"/>
        <link rel="stylesheet" href="/YHack/public/css/map.css"/>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>