<header>
  <h2 class="logo">
    Coupon
  </h2>
  <a class="nav">
    <img src="/YHack/public/images/nav.png" />
  </a>
</header>
<section id='map' class="map"></section>
<section class="locations">
  <ul id='location-list'>
    <li class="selected">
      <h2>
        Waiting
      </h2>
      <div class="distance">
        <img class="location" src="/YHack/public/images/location.png" />
      </div>
      <h4>
        Waiting on your location
      </h4>
    </li>
  </ul>
</section>


<script type="text/javascript">

function initialize() {
    var markers = [];
    var mapOptions = {
        center: new google.maps.LatLng(-34.397, 150.644),
        zoom: 14,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map"),
        mapOptions);
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function (position) {
            initialLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
            map.setCenter(initialLocation);
            placeMarker(map.getCenter());
        }, function(error) {
            alert(error.message);
        }, {
            timeout: '2000'
        });
    } else {
        alert("not supported");
    }

    function clearMarkers() {
        for (var i = 0; i < markers.length; i++)
            markers[i].setMap(null);
        markers = [];
    }

    function placeMarker(location) {
        clearMarkers();
        var marker = new google.maps.Marker({
            position: location,
            map: map
        });
        markers.push(marker);
    }

    function refresh()
    {
    	if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                var lat = position.coords.latitude;
                var lng = position.coords.longitude;
                var url = '<?php echo $this->url(array('controller'=>'coupon', 'action'=>'locate'), null, true) ?>';
                url += "?lat=" + lat + "&lng=" + lng;
                $.get(url, function(data) {
                    data = JSON.parse(data);
                    $("#location-list").empty();
                    for(var i = 0; i < data.length; i++)
                    {
                        console.log(data[i]);
                        var li = $("<li>");
                        var rightDiv = $("<div class='right'>");
                        var leftDiv = $("<div class='left'>");
                        leftDiv.append("<h2 class='inline'>" + data[i].coupon.title + "</h2>");
                        leftDiv.append("<span class='distance'><img class='location' src='/YHack/public/images/location.png' /> " + (data[i].meters/1000).toFixed(1) + " KM</span>");
                        leftDiv.append("<h4>" + data[i].coupon.description + "</h4>");
                        if(data[i].valid == true)
                            rightDiv.append("<button data-id='" + data[i].coupon._id.$id + "' class='active claim'>Claim</button>");
                        else if(data[i].claimed == true)
                            rightDiv.append("<button class='inactive claim'>Claimed</button>");
                        else if(data[i].valid != true)
                            rightDiv.append("<button class='inactive claim'>Unavail.</button>");
                        li.append(rightDiv);
                        li.append(leftDiv);
                        $("#location-list").append(li);
                    }
                });
            });
    	}
    }
    window.refresh = refresh;
    refresh();
   // setInterval(refresh, 15000);

    $("body").on("click", ".active.claim", function(e) {
        var self = $(this);
        navigator.geolocation.getCurrentPosition(function (position) {
        	var lat = position.coords.latitude;
            var lng = position.coords.longitude;
            var id = self.data('id');
            var url = '<?php echo $this->url(array('controller'=>'coupon', 'action'=>'redeem')) ?>';
            url += "?lat=" + lat + "&lng=" + lng + "&id=" + id;
            var postData = {lat: lat, lng: lng, id: id};
            $.post(url, postData, function(data) {
                data = JSON.parse(data);
                if(data['status'] == 200) {
                    //successful
                    self.removeClass("active").addClass("inactive").text("Claimed");
                    var di
                } else if(data['status'] == 500) {
                    //invalid but all filled out
                }
            });
        });
    });
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>